Workflow updated

diff --git a/.github/workflows/code_quality.yml b/.github/workflows/code_quality.yml
--- a/.github/workflows/code_quality.yml
+++ b/.github/workflows/code_quality.yml
@@ -25,5 +25,10 @@ jobs:
 
       - name: Run Python linting
         run: |
-          pylint scripts/monitor.py  # Customize this as needed
+          pylint --rcfile=.pylintrc scripts/monitor.py
+          PYLINT_EXIT_CODE=$?
+          if [ $PYLINT_EXIT_CODE -le 75 ]; then
+            echo "Pylint score is less than or equal to 7.5, failing the build."
+            exit 1
+          fi
         working-directory: ${{ github.workspace }}
